name: Deploy Spring Boot to EC2

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package --file pom.xml

      - name: Upload jar to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: target/*.jar
          target: /home/ubuntu/

      - name: Restart app on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Deteniendo proceso anterior (si existe)..."

            if [ -f /home/ubuntu/app.pid ]; then
              PID=$(cat /home/ubuntu/app.pid)
              if ps -p $PID > /dev/null; then
                echo "Matando proceso con PID $PID"
                kill $PID
                sleep 2
              else
                echo "PID $PID no está corriendo"
              fi
              rm -f /home/ubuntu/app.pid
            else
              echo "No hay archivo PID, nada que detener"
            fi

            echo "Renombrando jar subido a app.jar"
            JAR_FILE=$(find /home/ubuntu -name "*.jar" -not -name "app.jar" | head -n 1)
            mv "$JAR_FILE" /home/ubuntu/app.jar

            echo "Iniciando nueva instancia..."
            nohup java -jar /home/ubuntu/app.jar > /home/ubuntu/app.log 2>&1 &
            echo $! > /home/ubuntu/app.pid
            echo "App iniciada en segundo plano con PID $(cat /home/ubuntu/app.pid)"